name: "ESPHome Backup"
description: "Automated backup, retention, bundles and optional Git versioning for ESPHome YAML configurations."
version: "0.3.3"
slug: "esphome_backup"
init: false
startup: application
boot: auto
stage: experimental
ingress: true
ingress_port: 8099
panel_icon: "mdi:backup-restore"
panel_title: "ESPHome Backup"
panel_admin: true
arch:
  - amd64
  - aarch64
homeassistant_api: true
map:
  - type: homeassistant_config
    read_only: true
    path: /ha_config
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: backup
    read_only: false
options:
  destination: "/share/esphome-backup"
  destination_url: ""
  schedule: "03:30"
  run_on_start: true
  create_archive: true
  create_bundles: false
  include_secrets: true
  keep_daily: 14
  keep_weekly: 8
  keep_monthly: 12
  git_enabled: true
  git_remote: ""
  git_branch: "main"
  git_user_name: "ESPHome Backup"
  git_user_email: "esphome-backup@homeassistant.local"
  git_push: false
schema:
  destination: str
  destination_url: str?
  schedule: match(^([01]?[0-9]|2[0-3]):[0-5][0-9]$)
  run_on_start: bool
  create_archive: bool
  create_bundles: bool
  include_secrets: bool
  keep_daily: int(0,365)
  keep_weekly: int(0,104)
  keep_monthly: int(0,60)
  git_enabled: bool
  git_remote: str?
  git_branch: str
  git_user_name: str
  git_user_email: str
  git_push: bool
